DataDog/go-libddwaf

- .github/workflows/test.yml
- go.mod
As described in [this PR](https://github.com/DataDog/dd-trace-go/pull/1709), we are moving to version 1.18 as the minimal go version supported since go 1.20 has been released.
Bumping `go.mod` file and roll out 1.17 from the CI version matrix.
Tests still passes
> chore: bump minimal go version 1.17 -> 1.18

- .github/workflows/test.yml
Remove Ubuntu 18 from CI which is now deprecated.
> ci: remove deprecated ubuntu18

- .github/workflows/test.yml
macos 10.15 runners were disabled yesterday. Adding the new macos 13 runners
https://github.com/actions/runner-images/tree/main/images/macos
> rollout macos 10 in the CI

- waf.go
- waf_dl.go
- waf_dl_unsupported.go
- waf_test.go
- waf_unsupported_test.go
While integrating go-libddwaf v1.3.0 into dd-trace-go, we figured out that `Load()` was doing too much for the case of remote activation of appsec when in a disabled state, where we don't want to load libddwaf at all until appsec actually starts up remote activation order.
For this reason, we decided to make `Health()` useful again by replacing it with `SupportsTarget()` in order to be able to only check if we are on a supported target or not. This allows us to properly check for proper support of libddwaf, apart from the libddwaf loading, to do it early in the appsec startup and be able to properly log the information to the user.
> Public API: Replace Health() by SupportsTarget()

- .github/workflows/test.yml
- ctypes_test.go
- embed_darwin_amd64.go
- embed_linux_amd64.go
- embed_linux_arm64.go
- lib_dl.go
- symbols_linux_cgo.go
- symbols_linux_purego.go
- waf_dl.go
- waf_dl_test.go
- waf_dl_unsupported.go
- waf_test.go
- waf_unsupported_go.go
- waf_unsupported_target.go
- waf_unsupported_test.go
purego is panic'ing on go1.21's release candidate, which will be released in August.
With this PR, we will start enforcing the set of Go versions we know we support and explicitly disable future Go versions until we tested them ourselves. As a result, Go 1.21 is disabled for now until a fix is figured out.
> api: explicitly disable future go versions

- .github/workflows/test.yml
- waf_unsupported_go.go
Include more go1.21rc tests, as I figured out how to get the release candidate in the native jobs that were using `@actions/setup-go`.
> ci: native go1.21 tests

- ctypes_test.go
- embed_darwin_amd64.go
- embed_darwin_arm64.go
- embed_linux_amd64.go
- embed_linux_arm64.go
- go.mod
- go.sum
- lib_dl.go
- symbols_linux_cgo.go
- symbols_linux_purego.go
- waf_dl.go
- waf_dl_test.go
- waf_dl_unsupported.go
- waf_test.go
- waf_unsupported_go.go
- waf_unsupported_target.go
- waf_unsupported_test.go
As per ebitengine/purego#139 and ebitengine/purego#145. purego now works on Go 1.21
> enable go 1.21

- handle.go
- waf_test.go
This is to avoid users mistakenly passing a JSON string instead of the parsed object.
> fix: handle.NewHandle() now accepts map instead of any

- .github/workflows/test.yml
So we can configure branch protection to block out the merge button until CI has completely finished.
> chore: add simple merge target in GH workflows

- handle.go
- waf_test.go
This reverts commit 3def4df1c4a7aea6acfe8b80afad5e0f814c0654.
> Revert "fix: handle.NewHandle() now accepts map instead of any (#26)"

- context.go
- encoder.go
- go.mod
- handle.go
- waf_dl.go
- waf_dl_test.go
- waf_test.go
- waf_unsupported_test.go
And remove retract directive since we changed major
> Update go.mod file for v2

- internal/noopfree/noopfree.go
- internal/noopfree/noopfree.s
Go ASM symbols are not bound by the major versioning ABI breakage go imposes, therefore we must change the name of the symbol manually for the v1 and the v2 version to coexist in the same binary.
Example error:
```
link: duplicated definition of symbol _noop_free, from github.com/DataDog/go-libddwaf/internal/noopfree and github.com/DataDog/go-libddwaf/v2/internal/noopfree
```
> rename _noop_free -> _noop_free_v2

- .github/workflows/test.yml
- README.md
- ctypes_test.go
- encoder_decoder_test.go
- handle_test.go
- internal/lib/lib.go
- internal/lib/lib_darwin_amd64.go
- internal/lib/lib_darwin_arm64.go
- internal/lib/lib_linux_amd64.go
- internal/lib/lib_linux_arm64.go
- internal/noopfree/noopfree.s
- safe_test.go
- symbols_linux_cgo.go
- symbols_linux_purego.go
- waf.go
- waf_disabled_manually.go
- waf_dl.go
- waf_dl_test.go
- waf_dl_unsupported.go
- waf_manually_disabled_test.go
- waf_support.go
- waf_test.go
- waf_unsupported_go.go
- waf_unsupported_go_test.go
- waf_unsupported_target.go
- waf_unsupported_target_test.go
- waf_unsupported_test.go
> chore: add datadog.no_waf build tag

- context.go
This allows schema reporting when appsec is enabled even if no security event in returned by the WAF
> context: decode derivatives even when no event is generated

- context.go
- encoder.go
- handle.go
- safe.go
- waf.go
- waf_test.go
- Removes a leftover mutex on `Handle` that no longer served any purpose
- Acquiring the mutex on `Context` prior to calling `ddwaf_context_destroy` to avoid concurrent calls to `ddwaf_run`, as these are not thread-safe.
APPSEC-12585
> fix: adjust mutex handling around ddwaf_context

- .github/workflows/test.yml
- go.mod
- waf_manually_disabled.go
- waf_manually_disabled_test.go
- waf_support.go
- waf_unsupported_go.go
- waf_unsupported_go_test.go
- waf_unsupported_target.go
- waf_unsupported_target_test.go
Run tests with a comprehensive cartesian product of all configurations:
- Operating systems & architectures[^1]
- CGO_ENABLED or not
- Go runtimes: `1.19`, `1.20`, `1.21`
- Go tags: _none_, `datadog.no_waf`, `go1.22`[^2], `datadog.no_waf,go1.22`
This uncovered compatibility gaps in the matrix, which this PR fixes as well:
- unsupported platform or architecture + `datadog.no_waf`
- unsupported go runtime + unsupported platform
[^1]: Multiple architectures are only tested for linux platforms due to technical limitations
[^2]: `go1.22` is a stand-in for future go releases for which `purego` support needs checking
> Improve test matrix comprehensiveness

- ctypes.go
Turns out Go does not forward the previous declaration's type if the value is not implicitly iota.
> fix: appropriately type constants

- go.mod
- go.sum
Upgrade to get fix ebitengine/purego#189 from upstream
> go.mod: upgrade purego v0.5.1 => upgrade purego v0.5.2

- .github/workflows/_test_bare_metal.yml
- .github/workflows/_test_containerized.yml
- _tools/libddwaf-updater/update.go
- ctypes_test.go
- encoder_decoder_test.go
- go.mod
- go.sum
- internal/lib/lib.go
- internal/lib/lib_darwin_amd64.go
- internal/lib/lib_darwin_arm64.go
- internal/lib/lib_linux_amd64.go
- internal/lib/lib_linux_arm64.go
- internal/log/log_purego.go
- internal/log/log_unsupported.go
- symbols_linux_cgo.go
- symbols_linux_purego.go
- waf_dl.go
- waf_dl_test.go
- waf_dl_unsupported.go
- waf_test.go
- waf_unsupported_go.go
- waf_unsupported_go_test.go
> feat: go1.22 support

- encoder.go
- encoder_decoder_test.go
- waf.go
Instead of "silently" performing truncations unless they are required on the top-level value, the encode now keeps tabs on the truncations it performed, recording the set of un-truncated sizes for each truncation cause.
This information will subsequently be made visible to downstream WAF users so that it is possible to implement telemetry tracking of the real-world impact of encoding limits, and possibly gain insight into how to tune them for maximum efficiency.
> feat: WAFObject encoder produces truncation information

- encoder.go
- encoder_decoder_test.go
One of the sources of false positives are partial parsing using `json.RawMessage` for json parsing for example. Ignoring these kind of values during encoding makes the WAF more reliable and faster in case different types of byte slice aliases are present
> feat(encoder): coerce aliases of byte slices as byte slices

- .github/workflows/_test_bare_metal.yml
- .github/workflows/_test_containerized.yml
- .github/workflows/ci.sh
- encoder.go
- encoder_decoder_test.go
- handle_test.go
- waf_support.go
- waf_support_test.go
- waf_unsupported_go.go
- waf_unsupported_go_test.go
Pros:
* Decreased CI time: p50 ~ 30min -> 3min | p95 ~ 2h -> 10m
* More understandable
* Does not hit the github job limit if we need to add another OS or Arch
* Less arm64 jobs = overall less flakyness
Cons:
* shell
* Alpine packages and Windows makes the shell a little tricky
* We are still dependent on arm64 job length
> ci: tranfer part of the matrix to a shell script

- .github/workflows/test.yml
- waf_test.go
#73 inadvertently merged while attempting to use constants that were moved by #69. Somehow GitHub branch protection failed us (I'll make sure this PR considers that check as required).
> fix: unqualified use of constants moved

- .github/workflows/_test_bare_metal.yml
- .github/workflows/_test_containerized.yml
Moves testing for ARM64 to new "bare-metal" runners, and stop running these on QEMU in Docker. This provides a significant performance enhancement for these cases.
> chore: test ARM64 on bare metal

- .github/workflows/_test_bare_metal.yml
- .github/workflows/_test_containerized.yml
- .github/workflows/test.yml
Also removed 1.19 suite since the package's `go.mod` declares `go 1.20`...
> chore: also run containerized tests on ARM

- context.go
- encoder.go
- encoder_decoder_test.go
- timer/node_timer.go
- timer/timer.go
- waf.go
- waf_test.go
Please look at the Run function using the side-by-side view and not the inline diff view
> feat: context-wide timeout

- metrics.go
Discrepancies between the function returning the Stats struct and the Metrics() function
> fix: pointer receiver on a copied struct

- context.go
- encoder.go
- metrics.go
- waf_test.go
> fix: put back duration_ext metric as the top-level timer

- context.go
- metrics.go
- waf_test.go
> fix: report _dd.appsec.waf.duration even when the WAF does not match on anything

- .gitignore
Github's default [Go.gitignore](https://github.com/github/gitignore/blob/main/Go.gitignore#L8-L9) ignores `*.so` and `*.dylib` files. Projects using that default gitignore along with `go mod vendor` may find when adding the vendored files to git that the `libddwaf-linux-amd64.so` and related .so/.dylib files are skipped (resulting in later build failures due to missing .so files).
If we add these exclusion rules, it will ensure that projects using vendoring and the widely used gitignore rules will be prompted to track this libraries .so/.dylib files without any special effort.
> Ensure WAF static libraries get tracked in vendor/

- context.go
- go.mod
- go.sum
- handle.go
- internal/bindings/safe.go
- internal/support/waf_support.go
- waf.go
> refactor: go 1.20 spring cleanup

- README.md
- alignement_test.go
- cgo_ref_pool.go
- context.go
- decoder.go
- encoder.go
- encoder_decoder_test.go
- go.mod
- handle.go
- internal/bindings/safe.go
- internal/bindings/safe_test.go
- internal/bindings/waf_dl.go
- internal/bindings/waf_dl_test.go
- internal/log/log_cgo.go
- internal/log/log_purego.go
- internal/support/waf_cgo_disabled.go
- internal/support/waf_cgo_disabled_test.go
- internal/support/waf_manually_disabled.go
- internal/support/waf_manually_disabled_test.go
- internal/support/waf_unsupported_go.go
- internal/support/waf_unsupported_go_test.go
- internal/support/waf_unsupported_target.go
- internal/support/waf_unsupported_target_test.go
- timer/clock_test.go
- timer/timer_test.go
- waf.go
- waf_support_test.go
- waf_test.go
JIRA: APPSEC-52726
Update go.mod and module references to go-libbdwaf v3 version.
> (chore): move to v3

- cgo_ref_pool.go
Empty strings would be passed as null waf string objects, which the WAF doesn't handle in all cases.
While we wait for a WAF update to properly handle this, we set the waf object value for empty go strings to a null terminated empty C string representation.
This is band-aid solution that should get discarded once the WAF handles nullptr strings in all expected cases.
> fix: stop passing empty strings as null ptrs

- internal/log/log_cgo.go
Go semantic versionning makes it that we can have multiple major versions of the same module in the same binary. Since we exported an hard-coded symbol it breaks this possibility. This should not happen in practice for customers because noone is using go-libddwaf as-is except dd-trace-go & some DataDog backend code
The error:
```
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/bin/ld: /tmp/go-link-2237125540/000030.o: in function `ddwafLogCallbackFn':
/tmp/go-build/_cgo_export.c:27: multiple definition of `ddwafLogCallbackFn'; /tmp/go-link-2237125540/000023.o:/tmp/go-build/_cgo_export.c:27: first defined here
```
> fix conflicting symbols between v2 & v3

- .github/workflows/_test_bare_metal.yml
Remove `macos-11` runners because there are under brownout from GitHub.
> ci: remove deprecated runner macos-11

- .github/workflows/_test_containerized.yml
- .github/workflows/ci.sh
- _tools/libddwaf-updater/update.go
- alignement_test.go
- encoder_decoder_test.go
- handle_test.go
- internal/bindings/waf_dl.go
- internal/bindings/waf_dl_test.go
- internal/bindings/waf_dl_unsupported.go
- internal/lib/lib.go
- internal/lib/lib_darwin_amd64.go
- internal/lib/lib_darwin_arm64.go
- internal/lib/lib_linux_amd64.go
- internal/lib/lib_linux_arm64.go
- internal/log/log_purego.go
- internal/log/log_unsupported.go
- internal/support/waf_unsupported_go.go
- internal/support/waf_unsupported_go_test.go
- internal/support/waf_unsupported_target_test.go
- waf_test.go
> chore: unlock go 1.23

- .github/workflows/_test_bare_metal.yml
- .github/workflows/_test_containerized.yml
- .github/workflows/ci.sh
- encoder.go
- go.mod
- internal/bindings/waf_dl.go
- internal/lib/lib.go
- waf.go
> refactor: set go 1.21 as minimal supported version

- internal/bindings/waf_dl.go
Context: https://github.com/DataDog/go-libddwaf/pull/106#discussion_r1743244846
I am doing this on behave of @eliottness.
> Don't ignore errors during loading libddwaf shared library

- context.go
- handle.go
- metrics.go
- waf_test.go
> feat: WAF Run Scope support for RASP Metrics

- decoder.go
- errors/waf.go
- handle.go
- internal/bindings/safe.go
- internal/bindings/safe_test.go
- internal/bindings/waf_dl.go
- waf.go
I did random stuff to make things a little bit better
> refactor: misc

- .github/workflows/_test_bare_metal.yml
- .github/workflows/_test_containerized.yml
- .github/workflows/ci.sh
- _tools/libddwaf-updater/update.go
- alignement_test.go
- encoder.go
- encoder_decoder_test.go
- go.mod
- go.sum
- handle_test.go
- internal/bindings/ctypes.go
- internal/bindings/waf_dl.go
- internal/bindings/waf_dl_test.go
- internal/bindings/waf_dl_unsupported.go
- internal/lib/dump_waf_darwin.go
- internal/lib/dump_waf_linux.go
- internal/lib/lib_darwin_amd64.go
- internal/lib/lib_darwin_arm64.go
- internal/lib/lib_linux_amd64.go
- internal/lib/lib_linux_arm64.go
- internal/log/log_purego.go
- internal/log/log_unsupported.go
- internal/support/waf_unsupported_go.go
- internal/support/waf_unsupported_go_test.go
- waf.go
- waf_test.go
> chore: unlock go 1.24

- encoder.go
- errors/waf.go
- metrics.go
> fix: sync names for telemetry

- metrics.go
- timer/base_timer.go
- timer/component.go
- timer/config.go
- timer/node_timer.go
- timer/timer.go
- timer/timer_test.go
Introduction a new `timer.Key` type to better distinguish timer keys from the rest
Also remove a useless condition on `timer.NewNode` that will make testing the new API easier
> refactor(timer): replace raw strings by timer.Key for futur use

- .github/workflows/ci.sh
- _tools/libddwaf-updater/update.go
- alignement_test.go
- builder_test.go
- encoder_decoder_test.go
- internal/bindings/libddwaf.go
- internal/bindings/waf_dl.go
- internal/bindings/waf_dl_test.go
- internal/bindings/waf_dl_unsupported.go
- internal/lib/dump_waf_darwin.go
- internal/lib/dump_waf_linux.go
- internal/lib/lib_darwin_amd64.go
- internal/lib/lib_darwin_arm64.go
- internal/lib/lib_linux_amd64.go
- internal/lib/lib_linux_arm64.go
- internal/log/log_purego.go
- internal/log/log_unsupported.go
- internal/support/waf_unsupported_go.go
- internal/support/waf_unsupported_go_test.go
- waf_support_test.go
- waf_test.go
Allows go1.25 and introduces a "maybe supported" option in the CI script, as it's not certain whether a dev release is supported or not supported (and it being binary makes it impossible to do early testing).
> chore: support go1.25

- _tools/libddwaf-updater/go.mod
- _tools/ruleset-updater/go.mod
- encoder.go
- encoder_decoder_test.go
The `-` exclusion is only when `"-"` is as-is, not when it has trailers (e.g, `"-,"`)
> chore: fix '-' serialization tag handling

- .github/workflows/_test_bare_metal.yml
- internal/ruleset/ruleset.go
- internal/ruleset/ruleset_test.go
- internal/ruleset/ruleset_unsupported.go
This avoids risking to carry a large embedded JSON object on Windows binaries where it'll never be of any use. The DefaultRuleset function remains "live" because it's used by the Builder API which is part of the surface that is not / cannot be gated by a build tag.
> chore: don't bake-in the default ruleset on Windows
